/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GKartCategory service. Represents a row in the &quot;GKart_GKartCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.GKartCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.GKartCategoryImpl}.
 * </p>
 *
 * @author Valiyullah
 * @see GKartCategory
 * @see com.liferay.sample.model.impl.GKartCategoryImpl
 * @see com.liferay.sample.model.impl.GKartCategoryModelImpl
 * @generated
 */
public interface GKartCategoryModel extends BaseModel<GKartCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g kart category model instance should use the {@link GKartCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this g kart category.
	 *
	 * @return the primary key of this g kart category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g kart category.
	 *
	 * @param primaryKey the primary key of this g kart category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cat ID of this g kart category.
	 *
	 * @return the cat ID of this g kart category
	 */
	public long getCatId();

	/**
	 * Sets the cat ID of this g kart category.
	 *
	 * @param catId the cat ID of this g kart category
	 */
	public void setCatId(long catId);

	/**
	 * Returns the cat name of this g kart category.
	 *
	 * @return the cat name of this g kart category
	 */
	@AutoEscape
	public String getCatName();

	/**
	 * Sets the cat name of this g kart category.
	 *
	 * @param catName the cat name of this g kart category
	 */
	public void setCatName(String catName);

	/**
	 * Returns the subcatd ID of this g kart category.
	 *
	 * @return the subcatd ID of this g kart category
	 */
	public int getSubcatdId();

	/**
	 * Sets the subcatd ID of this g kart category.
	 *
	 * @param subcatdId the subcatd ID of this g kart category
	 */
	public void setSubcatdId(int subcatdId);

	/**
	 * Returns the subcat name of this g kart category.
	 *
	 * @return the subcat name of this g kart category
	 */
	@AutoEscape
	public String getSubcatName();

	/**
	 * Sets the subcat name of this g kart category.
	 *
	 * @param subcatName the subcat name of this g kart category
	 */
	public void setSubcatName(String subcatName);

	/**
	 * Returns the create date of this g kart category.
	 *
	 * @return the create date of this g kart category
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this g kart category.
	 *
	 * @param createDate the create date of this g kart category
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this g kart category.
	 *
	 * @return the modified date of this g kart category
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this g kart category.
	 *
	 * @param modifiedDate the modified date of this g kart category
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GKartCategory gKartCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GKartCategory> toCacheModel();

	@Override
	public GKartCategory toEscapedModel();

	@Override
	public GKartCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}