/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GKartItems service. Represents a row in the &quot;GKart_GKartItems&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.GKartItemsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.GKartItemsImpl}.
 * </p>
 *
 * @author Valiyullah
 * @see GKartItems
 * @see com.liferay.sample.model.impl.GKartItemsImpl
 * @see com.liferay.sample.model.impl.GKartItemsModelImpl
 * @generated
 */
public interface GKartItemsModel extends BaseModel<GKartItems> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g kart items model instance should use the {@link GKartItems} interface instead.
	 */

	/**
	 * Returns the primary key of this g kart items.
	 *
	 * @return the primary key of this g kart items
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g kart items.
	 *
	 * @param primaryKey the primary key of this g kart items
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item ID of this g kart items.
	 *
	 * @return the item ID of this g kart items
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this g kart items.
	 *
	 * @param itemId the item ID of this g kart items
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the cat name of this g kart items.
	 *
	 * @return the cat name of this g kart items
	 */
	@AutoEscape
	public String getCatName();

	/**
	 * Sets the cat name of this g kart items.
	 *
	 * @param catName the cat name of this g kart items
	 */
	public void setCatName(String catName);

	/**
	 * Returns the cat ID of this g kart items.
	 *
	 * @return the cat ID of this g kart items
	 */
	public int getCatId();

	/**
	 * Sets the cat ID of this g kart items.
	 *
	 * @param catId the cat ID of this g kart items
	 */
	public void setCatId(int catId);

	/**
	 * Returns the item name of this g kart items.
	 *
	 * @return the item name of this g kart items
	 */
	@AutoEscape
	public String getItemName();

	/**
	 * Sets the item name of this g kart items.
	 *
	 * @param itemName the item name of this g kart items
	 */
	public void setItemName(String itemName);

	/**
	 * Returns the item desc of this g kart items.
	 *
	 * @return the item desc of this g kart items
	 */
	@AutoEscape
	public String getItemDesc();

	/**
	 * Sets the item desc of this g kart items.
	 *
	 * @param itemDesc the item desc of this g kart items
	 */
	public void setItemDesc(String itemDesc);

	/**
	 * Returns the brand name of this g kart items.
	 *
	 * @return the brand name of this g kart items
	 */
	@AutoEscape
	public String getBrandName();

	/**
	 * Sets the brand name of this g kart items.
	 *
	 * @param brandName the brand name of this g kart items
	 */
	public void setBrandName(String brandName);

	/**
	 * Returns the price of this g kart items.
	 *
	 * @return the price of this g kart items
	 */
	public long getPrice();

	/**
	 * Sets the price of this g kart items.
	 *
	 * @param price the price of this g kart items
	 */
	public void setPrice(long price);

	/**
	 * Returns the quantity of this g kart items.
	 *
	 * @return the quantity of this g kart items
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this g kart items.
	 *
	 * @param quantity the quantity of this g kart items
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the units of this g kart items.
	 *
	 * @return the units of this g kart items
	 */
	@AutoEscape
	public String getUnits();

	/**
	 * Sets the units of this g kart items.
	 *
	 * @param units the units of this g kart items
	 */
	public void setUnits(String units);

	/**
	 * Returns the image of this g kart items.
	 *
	 * @return the image of this g kart items
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this g kart items.
	 *
	 * @param image the image of this g kart items
	 */
	public void setImage(String image);

	/**
	 * Returns the brand desc of this g kart items.
	 *
	 * @return the brand desc of this g kart items
	 */
	@AutoEscape
	public String getBrandDesc();

	/**
	 * Sets the brand desc of this g kart items.
	 *
	 * @param brandDesc the brand desc of this g kart items
	 */
	public void setBrandDesc(String brandDesc);

	/**
	 * Returns the create date of this g kart items.
	 *
	 * @return the create date of this g kart items
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this g kart items.
	 *
	 * @param createDate the create date of this g kart items
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this g kart items.
	 *
	 * @return the modified date of this g kart items
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this g kart items.
	 *
	 * @param modifiedDate the modified date of this g kart items
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GKartItems gKartItems);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GKartItems> toCacheModel();

	@Override
	public GKartItems toEscapedModel();

	@Override
	public GKartItems toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}